"""Create games table

Revision ID: 47ea5e3b316c
Revises:
Create Date: 2025-11-26 22:15:02.554988

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "47ea5e3b316c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column(
            "black_player_type",
            sa.Enum("AI", "HUMAN", name="playertype"),
            nullable=False,
        ),
        sa.Column("black_ai_id", sa.String(), nullable=True),
        sa.Column(
            "white_player_type",
            sa.Enum("AI", "HUMAN", name="playertype"),
            nullable=False,
        ),
        sa.Column("white_ai_id", sa.String(), nullable=True),
        sa.Column(
            "winner",
            sa.Enum("BLACK", "WHITE", "DRAW", name="winner"),
            nullable=False,
        ),
        sa.Column("black_score", sa.Integer(), nullable=False),
        sa.Column("white_score", sa.Integer(), nullable=False),
        sa.Column("total_moves", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    # ### end Alembic commands ###
